insert into dyscyplina values (1,'Analitycy');
insert into dyscyplina values (2,'Wymagania');
insert into dyscyplina values (3,'Implementacja');
insert into dyscyplina values (4,'Modelowanie biznesowe');
insert into dyscyplina values (5,'Analiza i projekt');
insert into dyscyplina values (6,'Testy');
insert into dyscyplina values (7,'Konfiguracja i zarządzanie zmianami');
insert into dyscyplina values (8,'Zarządzanie projektem ');
insert into dyscyplina values (9,'Zarządzanie środowiskami');
insert into rola values (1,2,'Analityk systemowy');
insert into rola values (2,2,'Specyfikator wymagań');
insert into rola values (3,4,'Architekt biznesowy');
insert into rola values (4,4,'Analityk procesów biznesowych');
insert into rola values (5,5,'Architekt oprogramowania');
insert into rola values (6,5,'Projektant bazodanowy');
insert into rola values (7,5,'Projektant inferfejsu uzytkownika');
insert into rola values (8,5,'Projektant');
insert into rola values (9,3,'Integrator');
insert into rola values (10,3,'Realizator');
insert into rola values (11,3,'Architekt oprogramowania');
insert into rola values (12,6,'Projektant testowy');
insert into rola values (13,6,'Analityk testowy');
insert into rola values (14,6,'Manager testów');
insert into rola values (15,6,'Tester');
insert into rola values (16,7,'Manager zmian');
insert into rola values (17,7,'Manager konfiguracji');
insert into rola values (18,9,'Administrator systemu');
insert into rola values (19,8,'Inżynier procesu');
insert into rola values (20,8,'Mangar projektu');
insert into rola values (21,8,'Manager wdrażania');
insert into rola values (22,8,'Koordynator ');

insert into Slownik_produkt values (1,'Słownik (glosariusz)');
insert into Slownik_produkt values (2,'Requirements Attributes');
insert into Slownik_produkt values (3,'Requirements Management Plan');
insert into Slownik_produkt values (4,'Wymagania systemowe');
insert into Slownik_produkt values (5,'Specyfikacja wymagań systemowych');
insert into Slownik_produkt values (6,'Żądania udziałowców');
insert into Slownik_produkt values (7,'Scenariusz ');
insert into Slownik_produkt values (8,'Specyfikacja dodtkowa');
insert into Slownik_produkt values (9,'Model przypadków użycia');
insert into Slownik_produkt values (10,'Wizja');
insert into Slownik_produkt values (11,'Biznesowy model analityczny');
insert into Slownik_produkt values (12,'Model biznesowych przypadków użycia');
insert into Slownik_produkt values (13,'Słownik biznesowy');
insert into Slownik_produkt values (14,'Wizja biznesowa');
insert into Slownik_produkt values (15,'Oszacowanie celu organizacji');
insert into Slownik_produkt values (16,'Architektura biznesowa');
insert into Slownik_produkt values (17,'Biznesowy model wdrożenia');
insert into Slownik_produkt values (18,'Biznesowy model projektowy');
insert into Slownik_produkt values (19,'Business Architectural Proof-of-Concept');
insert into Slownik_produkt values (20,'Supplementary Business Specification');
insert into Slownik_produkt values (21,'Role biznesowe');
insert into Slownik_produkt values (22,'Cele biznesowe');
insert into Slownik_produkt values (23,'Business Domain');
insert into Slownik_produkt values (24,'Model analityczny');
insert into Slownik_produkt values (25,'Architectural Proof-of-Concept');
insert into Slownik_produkt values (26,'Specyfikacja migracji danych');
insert into Slownik_produkt values (27,'Model danych');
insert into Slownik_produkt values (28,'Model wdrożeniowy');
insert into Slownik_produkt values (29,'Model projektowy');
insert into Slownik_produkt values (30,'Goal-Service Model');
insert into Slownik_produkt values (31,'Navigation Map');
insert into Slownik_produkt values (32,'Reference Architecture');
insert into Slownik_produkt values (33,'Service Model');
insert into Slownik_produkt values (34,'Dokumentacja architektury programu');
insert into Slownik_produkt values (35,'Prototyp interfejsu');
insert into Slownik_produkt values (36,'Skompilowane działające kawałki kodu');
insert into Slownik_produkt values (37,'Testy wytwórcze');
insert into Slownik_produkt values (38,'Model implementacyjny');
insert into Slownik_produkt values (39,'Plan integracji');
insert into Slownik_produkt values (40,'Test Automation Architektura');
insert into Slownik_produkt values (41,'Pyrzpadki testowe');
insert into Slownik_produkt values (42,'Dane testowe');
insert into Slownik_produkt values (43,'Projekt testowy');
insert into Slownik_produkt values (44,'Konfiguracja środowiska testowego ');
insert into Slownik_produkt values (45,'Testy podsumowujące');
insert into Slownik_produkt values (46,'Test Interface Specification');
insert into Slownik_produkt values (47,'Logi testu');
insert into Slownik_produkt values (48,'Plan testu');
insert into Slownik_produkt values (49,'Wyniki testu');
insert into Slownik_produkt values (50,'Skrypt testowy');
insert into Slownik_produkt values (51,'Strategia testowania');
insert into Slownik_produkt values (52,'Test Suite');
insert into Slownik_produkt values (53,'Test-Ideas List');
insert into Slownik_produkt values (54,'Workload Analysis Model');
insert into Slownik_produkt values (55,'Change Request');
insert into Slownik_produkt values (56,'Ustalenia kontroli konfiguracji');
insert into Slownik_produkt values (57,'Plan zarządzania konfiguracją');
insert into Slownik_produkt values (58,'Project Repository');
insert into Slownik_produkt values (59,'Workspace');
insert into Slownik_produkt values (60,'Development Infrastructure');
insert into Slownik_produkt values (61,'Development Organization Assessment');
insert into Slownik_produkt values (62,'Proces rozwoju');
insert into Slownik_produkt values (63,'Przypadki biznesowe');
insert into Slownik_produkt values (64,'Plan rozmieszczenia');
insert into Slownik_produkt values (65,'Lista zagadnienia');
insert into Slownik_produkt values (66,'Ocena iteracji');
insert into Slownik_produkt values (67,'Plan iteracji');
insert into Slownik_produkt values (68,'Pomiary projektowe');
insert into Slownik_produkt values (69,'Przegląd ');
insert into Slownik_produkt values (70,'Lista ryzyka');
insert into Slownik_produkt values (71,'Plan Rozwoju Oprogramowania');
insert into Slownik_produkt values (72,'Oceny stanu');
insert into Slownik_produkt values (73,'Porządek pracy');

insert into Slownik_czynnosc values (1,'Stworzenie słownika');
insert into Slownik_czynnosc values (2,'Określ kontekst systemu');
insert into Slownik_czynnosc values (3,'Opracowanie planu zarządzania wymaganiami');
insert into Slownik_czynnosc values (4,'Opracowanie specyfikacji uzupełniających');
insert into Slownik_czynnosc values (5,'Opracowanie wizji');
insert into Slownik_czynnosc values (6,'Zdobycie żądań interesariuszy');
insert into Slownik_czynnosc values (7,'Opracowanie aktorów i przypadków użycia');
insert into Slownik_czynnosc values (8,'Zarządzanie zależnościami');
insert into Slownik_czynnosc values (9,'Struktura modelu przypadków użycia');
insert into Slownik_czynnosc values (10,'Szczegóły przypadków użycia');
insert into Slownik_czynnosc values (11,'Szczegóły wymagań programowych');
insert into Slownik_czynnosc values (12,'Analiza biznesowa architektoniczne');
insert into Slownik_czynnosc values (13,'Konstruowanie architektury biznesowej');
insert into Slownik_czynnosc values (14,'Analiza funkcjonalna');
insert into Slownik_czynnosc values (15,'Priorytetowanie biznesowych przypadków użycia');
insert into Slownik_czynnosc values (16,'Ocenna organizacji');
insert into Slownik_czynnosc values (17,'Stworzenie słownika biznesowego');
insert into Slownik_czynnosc values (18,'Określenie kontekst systemu biznesowego');
insert into Slownik_czynnosc values (19,'Opracowanie aktorów biznesowych i przypadków użycia');
insert into Slownik_czynnosc values (20,'Określić cele biznesowe i KPI');
insert into Slownik_czynnosc values (21,'Utrzymanie reguł biznesowych');
insert into Slownik_czynnosc values (22,'Ograniczenie zastosowań do przypadków biznesowych');
insert into Slownik_czynnosc values (23,'Ustawianie i dostosowanie celów');
insert into Slownik_czynnosc values (24,'Budowa modelu biznesowych przypadków użycia');
insert into Slownik_czynnosc values (25,'Zastosowanie usług testów');
insert into Slownik_czynnosc values (26,'Analiza architektoniczna');
insert into Slownik_czynnosc values (27,'Assess Visibility of Architectural Proof - of - Concept ');
insert into Slownik_czynnosc values (28,'Analiza Procesów Biznesowych');
insert into Slownik_czynnosc values (29,'Analiza reguł biznesowych');
insert into Slownik_czynnosc values (30,'Construct Architectural Proof - of - Concept (SOA)');
insert into Slownik_czynnosc values (31,'Analiza modelu danych');
insert into Slownik_czynnosc values (32,'Describe Distribution');
insert into Slownik_czynnosc values (33,'Describe the Run - time Architecture');
insert into Slownik_czynnosc values (34,'Analiza istniejących aktywów');
insert into Slownik_czynnosc values (35,'Włączenie istniejących elementów projektu');
insert into Slownik_czynnosc values (36,'Priorytet przypadków użycia');
insert into Slownik_czynnosc values (37,'Budowa Modelu Realizacji');
insert into Slownik_czynnosc values (38,'Projekt bazy danych');
insert into Slownik_czynnosc values (39,'Określ migracji danych');
insert into Slownik_czynnosc values (40,'Projektowanie interfejsu użytkownika');
insert into Slownik_czynnosc values (41,'Prototyp interfejsu użytkownika');
insert into Slownik_czynnosc values (42,'Capsule Design');
insert into Slownik_czynnosc values (43,'Create Baselines ');
insert into Slownik_czynnosc values (44,'Tworzenie integracyjnych obszarów roboczych');
insert into Slownik_czynnosc values (45,'Zintegrowanie Subsystemu');
insert into Slownik_czynnosc values (46,'Zintegrowanie systemu');
insert into Slownik_czynnosc values (47,'Plan integracji podsystemu');
insert into Slownik_czynnosc values (48,'Plan integracji systemu');
insert into Slownik_czynnosc values (49,'Promote Baselines');
insert into Slownik_czynnosc values (50,'Analyze Runtime Behavior');
insert into Slownik_czynnosc values (51,'Develop Installation Work Products');
insert into Slownik_czynnosc values (52,'Execute Developer Tests');
insert into Slownik_czynnosc values (53,'Implement Design Elements');
insert into Slownik_czynnosc values (54,'Implement Developer Test');
insert into Slownik_czynnosc values (55,'Implement Testablity Elements');
insert into Slownik_czynnosc values (56,'Define Test Approach');
insert into Slownik_czynnosc values (57,'Define Test Enviroment Configuration');
insert into Slownik_czynnosc values (58,'Define Testability Elements');
insert into Slownik_czynnosc values (59,'Identify Testability Mechanisms');
insert into Slownik_czynnosc values (60,'Sructure the Test Implementantion');
insert into Slownik_czynnosc values (61,'Define Assessment and Tracebility Needs');
insert into Slownik_czynnosc values (62,'Define Test Details');
insert into Slownik_czynnosc values (63,'Determine Test Results');
insert into Slownik_czynnosc values (64,'Identify Targets of Test');
insert into Slownik_czynnosc values (65,'Identify Targets Ideas');
insert into Slownik_czynnosc values (66,'Verify Changes inn Build');
insert into Slownik_czynnosc values (67,'Agree on the Mission');
insert into Slownik_czynnosc values (68,'Assess and Advocate Quality');
insert into Slownik_czynnosc values (69,'Assess and Improve Test Effort');
insert into Slownik_czynnosc values (70,'Identify Test Motivators');
insert into Slownik_czynnosc values (71,'Obtain Testability Commintment');
insert into Slownik_czynnosc values (72,'Analyze Test Failure');
insert into Slownik_czynnosc values (73,'Execute Test Suite');
insert into Slownik_czynnosc values (74,'Implement Test');
insert into Slownik_czynnosc values (75,'Implement Test Suite');
insert into Slownik_czynnosc values (76,'Confirm Duplicate or Rejected CR');
insert into Slownik_czynnosc values (77,'Establish Change Control Process');
insert into Slownik_czynnosc values (78,'Review Change Requests');
insert into Slownik_czynnosc values (79,'Create Deployment Unit');
insert into Slownik_czynnosc values (80,'Establish Configuration Managment (CM)');
insert into Slownik_czynnosc values (81,'Perform Configuration Audit');
insert into Slownik_czynnosc values (82,'Report on Configuration Status');
insert into Slownik_czynnosc values (83,'Set Up Configuration Managment (CM)');
insert into Slownik_czynnosc values (84,'Write Configuration Managment (CM) Plan');
insert into Slownik_czynnosc values (85,'Support Development');
insert into Slownik_czynnosc values (86,'Develop Development Case');
insert into Slownik_czynnosc values (87,'Launch Development Process');
insert into Slownik_czynnosc values (88,'Prepare Guidelines for the Project');
insert into Slownik_czynnosc values (89,'pPrepare Templates for the Project');
insert into Slownik_czynnosc values (90,'Tailor the Development Process for the');
insert into Slownik_czynnosc values (91,'Acquire Staff ');
insert into Slownik_czynnosc values (92,'Assess Iteration');
insert into Slownik_czynnosc values (93,'Compile Software Development Pla');
insert into Slownik_czynnosc values (94,'Define Monitoring & Control Processes');
insert into Slownik_czynnosc values (95,'Define Project Organization and Staffing ');
insert into Slownik_czynnosc values (96,'Develop Business Case');
insert into Slownik_czynnosc values (97,'Develop Iteration Plan');
insert into Slownik_czynnosc values (98,'Develop Measurement Plan');
insert into Slownik_czynnosc values (99,'Develop Problem Resolution Plan');
insert into Slownik_czynnosc values (100,'Develop Product Acceptance Plan');
insert into Slownik_czynnosc values (101,'Develop Quality Assurance Plan');
insert into Slownik_czynnosc values (102,'Develop Risk Manegment Plan');
insert into Slownik_czynnosc values (103,'Handle Exceptions and Problems');
insert into Slownik_czynnosc values (104,'Idenitify and Assess Risks');
insert into Slownik_czynnosc values (105,'Initiate Iteration ');
insert into Slownik_czynnosc values (106,'Initiate Project');
insert into Slownik_czynnosc values (107,'monitor Project Status');
insert into Slownik_czynnosc values (108,'Plan Phases and Iterations');
insert into Slownik_czynnosc values (109,'Prepare for Phase Close - Out');
insert into Slownik_czynnosc values (110,'Report Status');
insert into Slownik_czynnosc values (111,'Schedule and Assign Work');
insert into Slownik_czynnosc values (112,'Defie Bill of Materials ');
insert into Slownik_czynnosc values (113,'Develop Deployment Plan');
insert into Slownik_czynnosc values (114,'Manage Acceptance Test');
insert into Slownik_czynnosc values (115,'Manage Beta Test');
insert into Slownik_czynnosc values (116,'Provide Access to Download Site');
insert into Slownik_czynnosc values (117,'Relase to Manufucturing');
insert into Slownik_czynnosc values (118,'Rverify Manufactered Product');
insert into Slownik_czynnosc values (119,'Write Relase Notes');
insert into Slownik_czynnosc values (120,'Organize Review');

insert into zaleznosc_rola_czynnosc values (1,1,1);
insert into zaleznosc_rola_czynnosc values (2,1,2);
insert into zaleznosc_rola_czynnosc values (3,1,3);
insert into zaleznosc_rola_czynnosc values (4,1,4);
insert into zaleznosc_rola_czynnosc values (5,1,5);
insert into zaleznosc_rola_czynnosc values (6,1,6);
insert into zaleznosc_rola_czynnosc values (7,1,7);
insert into zaleznosc_rola_czynnosc values (8,1,8);
insert into zaleznosc_rola_czynnosc values (9,1,9);
insert into zaleznosc_rola_czynnosc values (10,2,10);
insert into zaleznosc_rola_czynnosc values (11,2,11);
insert into zaleznosc_rola_czynnosc values (12,3,12);
insert into zaleznosc_rola_czynnosc values (13,3,13);
insert into zaleznosc_rola_czynnosc values (14,3,14);
insert into zaleznosc_rola_czynnosc values (15,3,15);
insert into zaleznosc_rola_czynnosc values (16,4,16);
insert into zaleznosc_rola_czynnosc values (17,4,17);
insert into zaleznosc_rola_czynnosc values (18,4,18);
insert into zaleznosc_rola_czynnosc values (19,4,19);
insert into zaleznosc_rola_czynnosc values (20,4,20);
insert into zaleznosc_rola_czynnosc values (21,4,21);
insert into zaleznosc_rola_czynnosc values (22,4,22);
insert into zaleznosc_rola_czynnosc values (23,4,23);
insert into zaleznosc_rola_czynnosc values (24,4,24);
insert into zaleznosc_rola_czynnosc values (25,5,25);
insert into zaleznosc_rola_czynnosc values (26,5,26);
insert into zaleznosc_rola_czynnosc values (27,5,27);
insert into zaleznosc_rola_czynnosc values (28,5,28);
insert into zaleznosc_rola_czynnosc values (29,5,29);
insert into zaleznosc_rola_czynnosc values (30,5,30);
insert into zaleznosc_rola_czynnosc values (31,5,31);
insert into zaleznosc_rola_czynnosc values (32,5,32);
insert into zaleznosc_rola_czynnosc values (33,5,33);
insert into zaleznosc_rola_czynnosc values (34,5,34);
insert into zaleznosc_rola_czynnosc values (35,5,35);
insert into zaleznosc_rola_czynnosc values (36,5,36);
insert into zaleznosc_rola_czynnosc values (37,5,37);
insert into zaleznosc_rola_czynnosc values (38,6,38);
insert into zaleznosc_rola_czynnosc values (39,6,39);
insert into zaleznosc_rola_czynnosc values (40,7,40);
insert into zaleznosc_rola_czynnosc values (41,7,41);
insert into zaleznosc_rola_czynnosc values (42,8,42);
insert into zaleznosc_rola_czynnosc values (43,9,43);
insert into zaleznosc_rola_czynnosc values (44,9,44);
insert into zaleznosc_rola_czynnosc values (45,9,45);
insert into zaleznosc_rola_czynnosc values (46,9,46);
insert into zaleznosc_rola_czynnosc values (47,9,47);
insert into zaleznosc_rola_czynnosc values (48,9,48);
insert into zaleznosc_rola_czynnosc values (49,9,49);
insert into zaleznosc_rola_czynnosc values (50,10,50);
insert into zaleznosc_rola_czynnosc values (51,10,51);
insert into zaleznosc_rola_czynnosc values (52,10,52);
insert into zaleznosc_rola_czynnosc values (53,10,53);
insert into zaleznosc_rola_czynnosc values (54,10,54);
insert into zaleznosc_rola_czynnosc values (55,10,55);
insert into zaleznosc_rola_czynnosc values (56,11,56);
insert into zaleznosc_rola_czynnosc values (57,11,57);
insert into zaleznosc_rola_czynnosc values (58,11,58);
insert into zaleznosc_rola_czynnosc values (59,11,59);
insert into zaleznosc_rola_czynnosc values (60,11,60);
insert into zaleznosc_rola_czynnosc values (61,12,61);
insert into zaleznosc_rola_czynnosc values (62,12,62);
insert into zaleznosc_rola_czynnosc values (63,12,63);
insert into zaleznosc_rola_czynnosc values (64,12,64);
insert into zaleznosc_rola_czynnosc values (65,12,65);
insert into zaleznosc_rola_czynnosc values (66,12,66);
insert into zaleznosc_rola_czynnosc values (67,13,67);
insert into zaleznosc_rola_czynnosc values (68,13,68);
insert into zaleznosc_rola_czynnosc values (69,13,69);
insert into zaleznosc_rola_czynnosc values (70,13,70);
insert into zaleznosc_rola_czynnosc values (71,13,71);
insert into zaleznosc_rola_czynnosc values (72,14,72);
insert into zaleznosc_rola_czynnosc values (73,14,73);
insert into zaleznosc_rola_czynnosc values (74,14,74);
insert into zaleznosc_rola_czynnosc values (75,14,75);
insert into zaleznosc_rola_czynnosc values (76,15,76);
insert into zaleznosc_rola_czynnosc values (77,15,77);
insert into zaleznosc_rola_czynnosc values (78,15,78);
insert into zaleznosc_rola_czynnosc values (79,16,79);
insert into zaleznosc_rola_czynnosc values (80,16,80);
insert into zaleznosc_rola_czynnosc values (81,16,81);
insert into zaleznosc_rola_czynnosc values (82,16,82);
insert into zaleznosc_rola_czynnosc values (83,16,83);
insert into zaleznosc_rola_czynnosc values (84,16,84);
insert into zaleznosc_rola_czynnosc values (85,17,85);
insert into zaleznosc_rola_czynnosc values (86,18,86);
insert into zaleznosc_rola_czynnosc values (87,18,87);
insert into zaleznosc_rola_czynnosc values (88,18,88);
#N/D!
insert into zaleznosc_rola_czynnosc values (90,18,90);
insert into zaleznosc_rola_czynnosc values (91,19,91);
insert into zaleznosc_rola_czynnosc values (92,19,92);
insert into zaleznosc_rola_czynnosc values (93,19,93);
insert into zaleznosc_rola_czynnosc values (94,19,94);
insert into zaleznosc_rola_czynnosc values (95,19,95);
insert into zaleznosc_rola_czynnosc values (96,19,96);
insert into zaleznosc_rola_czynnosc values (97,19,97);
insert into zaleznosc_rola_czynnosc values (98,19,98);
insert into zaleznosc_rola_czynnosc values (99,19,99);
insert into zaleznosc_rola_czynnosc values (100,19,100);
insert into zaleznosc_rola_czynnosc values (101,19,101);
insert into zaleznosc_rola_czynnosc values (102,19,102);
insert into zaleznosc_rola_czynnosc values (103,19,103);
insert into zaleznosc_rola_czynnosc values (104,19,104);
insert into zaleznosc_rola_czynnosc values (105,19,105);
insert into zaleznosc_rola_czynnosc values (106,19,106);
insert into zaleznosc_rola_czynnosc values (107,19,107);
insert into zaleznosc_rola_czynnosc values (108,19,108);
insert into zaleznosc_rola_czynnosc values (109,19,109);
insert into zaleznosc_rola_czynnosc values (110,19,110);
insert into zaleznosc_rola_czynnosc values (111,19,111);
insert into zaleznosc_rola_czynnosc values (112,20,112);
insert into zaleznosc_rola_czynnosc values (113,20,113);
insert into zaleznosc_rola_czynnosc values (114,20,114);
insert into zaleznosc_rola_czynnosc values (115,20,115);
insert into zaleznosc_rola_czynnosc values (116,20,116);
insert into zaleznosc_rola_czynnosc values (117,20,117);
insert into zaleznosc_rola_czynnosc values (118,20,118);
insert into zaleznosc_rola_czynnosc values (119,20,119);
insert into zaleznosc_rola_czynnosc values (120,21,120);

insert into zaleznosc_rola_produkt values(1,1,1);
insert into zaleznosc_rola_produkt values(2,1,2);
insert into zaleznosc_rola_produkt values(3,1,3);
insert into zaleznosc_rola_produkt values(4,2,4);
insert into zaleznosc_rola_produkt values(5,2,5);
insert into zaleznosc_rola_produkt values(6,1,6);
insert into zaleznosc_rola_produkt values(7,1,7);
insert into zaleznosc_rola_produkt values(8,1,8);
insert into zaleznosc_rola_produkt values(9,1,9);
insert into zaleznosc_rola_produkt values(10,1,10);
insert into zaleznosc_rola_produkt values(11,3,11);
insert into zaleznosc_rola_produkt values(12,4,12);
insert into zaleznosc_rola_produkt values(13,4,13);
insert into zaleznosc_rola_produkt values(14,4,14);
insert into zaleznosc_rola_produkt values(15,4,15);
insert into zaleznosc_rola_produkt values(16,3,16);
insert into zaleznosc_rola_produkt values(17,3,17);
insert into zaleznosc_rola_produkt values(18,3,18);
insert into zaleznosc_rola_produkt values(19,3,19);
insert into zaleznosc_rola_produkt values(20,4,20);
insert into zaleznosc_rola_produkt values(21,4,21);
insert into zaleznosc_rola_produkt values(22,4,22);
insert into zaleznosc_rola_produkt values(23,5,24);
insert into zaleznosc_rola_produkt values(24,5,25);
insert into zaleznosc_rola_produkt values(25,6,26);
insert into zaleznosc_rola_produkt values(26,6,27);
insert into zaleznosc_rola_produkt values(27,5,28);
insert into zaleznosc_rola_produkt values(28,5,29);
insert into zaleznosc_rola_produkt values(29,5,30);
insert into zaleznosc_rola_produkt values(30,7,31);
insert into zaleznosc_rola_produkt values(31,5,32);
insert into zaleznosc_rola_produkt values(32,8,33);
insert into zaleznosc_rola_produkt values(33,5,34);
insert into zaleznosc_rola_produkt values(34,7,35);
insert into zaleznosc_rola_produkt values(35,9,36);
insert into zaleznosc_rola_produkt values(36,10,37);
insert into zaleznosc_rola_produkt values(37,5,38);
insert into zaleznosc_rola_produkt values(38,9,39);
insert into zaleznosc_rola_produkt values(39,11,40);
insert into zaleznosc_rola_produkt values(40,12,41);
insert into zaleznosc_rola_produkt values(41,12,42);
insert into zaleznosc_rola_produkt values(42,11,43);
insert into zaleznosc_rola_produkt values(43,11,44);
insert into zaleznosc_rola_produkt values(44,13,45);
insert into zaleznosc_rola_produkt values(45,11,46);
insert into zaleznosc_rola_produkt values(46,14,47);
insert into zaleznosc_rola_produkt values(47,13,48);
insert into zaleznosc_rola_produkt values(48,12,49);
insert into zaleznosc_rola_produkt values(49,14,50);
insert into zaleznosc_rola_produkt values(50,11,51);
insert into zaleznosc_rola_produkt values(51,11,52);
insert into zaleznosc_rola_produkt values(52,12,53);
insert into zaleznosc_rola_produkt values(53,12,54);
insert into zaleznosc_rola_produkt values(54,15,55);
insert into zaleznosc_rola_produkt values(55,16,56);
insert into zaleznosc_rola_produkt values(56,16,57);
insert into zaleznosc_rola_produkt values(57,16,58);
insert into zaleznosc_rola_produkt values(58,17,60);
insert into zaleznosc_rola_produkt values(59,18,62);
insert into zaleznosc_rola_produkt values(60,19,63);
insert into zaleznosc_rola_produkt values(61,20,64);
insert into zaleznosc_rola_produkt values(62,19,65);
insert into zaleznosc_rola_produkt values(63,19,66);
insert into zaleznosc_rola_produkt values(64,19,67);
insert into zaleznosc_rola_produkt values(65,19,68);
insert into zaleznosc_rola_produkt values(66,21,69);
insert into zaleznosc_rola_produkt values(67,19,70);
insert into zaleznosc_rola_produkt values(68,19,71);
insert into zaleznosc_rola_produkt values(69,19,72);
insert into zaleznosc_rola_produkt values(70,19,73);








---------------------------------
---------------------------------
---------------------------------
---------------------------------
---------------------------------



insert into pytania values (1,'projekt do roku');
insert into pytania values (2,'projekt do dwóch lat');
insert into pytania values (3,'projekt powyżej dwóch lat');
insert into pytania values (4,'projekt nowy');
insert into pytania values (5,'projekt utrzymaniowy');
insert into pytania values (6,'projekt rozwojowu');
insert into pytania values (7,'przewidywana liczba wymagań');
insert into pytania values (8,'czy testy mają być wykonane po stronie dostawcy rozwiązania czy zleceniodawcy?');
insert into pytania values (9,'Ile użytkowników ma korzystać z systemu?');
insert into pytania values (10,'czy system będzie integrował się z systemami zewnętrznymi');
insert into pytania values (11,'czy system ma spełniać standardy bezpieczeństwa?');
insert into pytania values (12,'czy BD? - NIE = zostają jedynki');
insert into pytania values (13,'czy chcesz, żeby GUI projektował UX Designer?  - NIE = zostają jedynki');
insert into pytania values (14,'przewidywany fundusz');



insert into Zaleznosc_pytania_rola values(1,1,1,1);
insert into Zaleznosc_pytania_rola values(2,2,1,1);
insert into Zaleznosc_pytania_rola values(3,3,1,0);
insert into Zaleznosc_pytania_rola values(4,4,1,0);
insert into Zaleznosc_pytania_rola values(5,5,1,1);
insert into Zaleznosc_pytania_rola values(6,6,1,1);
insert into Zaleznosc_pytania_rola values(7,7,1,1);
insert into Zaleznosc_pytania_rola values(8,8,1,0);
insert into Zaleznosc_pytania_rola values(9,9,1,1);
insert into Zaleznosc_pytania_rola values(10,10,1,1);
insert into Zaleznosc_pytania_rola values(11,11,1,0);
insert into Zaleznosc_pytania_rola values(12,12,1,1);
insert into Zaleznosc_pytania_rola values(13,13,1,1);
insert into Zaleznosc_pytania_rola values(14,14,1,1);
insert into Zaleznosc_pytania_rola values(15,15,1,1);
insert into Zaleznosc_pytania_rola values(16,16,1,1);
insert into Zaleznosc_pytania_rola values(17,17,1,1);
insert into Zaleznosc_pytania_rola values(18,18,1,1);
insert into Zaleznosc_pytania_rola values(19,19,1,1);
insert into Zaleznosc_pytania_rola values(20,20,1,1);
insert into Zaleznosc_pytania_rola values(21,21,1,1);
insert into Zaleznosc_pytania_rola values(22,22,1,1);
insert into Zaleznosc_pytania_rola values(23,1,2,1);
insert into Zaleznosc_pytania_rola values(24,2,2,1);
insert into Zaleznosc_pytania_rola values(25,3,2,1);
insert into Zaleznosc_pytania_rola values(26,4,2,1);
insert into Zaleznosc_pytania_rola values(27,5,2,1);
insert into Zaleznosc_pytania_rola values(28,6,2,1);
insert into Zaleznosc_pytania_rola values(29,7,2,1);
insert into Zaleznosc_pytania_rola values(30,8,2,1);
insert into Zaleznosc_pytania_rola values(31,9,2,1);
insert into Zaleznosc_pytania_rola values(32,10,2,1);
insert into Zaleznosc_pytania_rola values(33,11,2,1);
insert into Zaleznosc_pytania_rola values(34,12,2,1);
insert into Zaleznosc_pytania_rola values(35,13,2,1);
insert into Zaleznosc_pytania_rola values(36,14,2,1);
insert into Zaleznosc_pytania_rola values(37,15,2,1);
insert into Zaleznosc_pytania_rola values(38,16,2,1);
insert into Zaleznosc_pytania_rola values(39,17,2,1);
insert into Zaleznosc_pytania_rola values(40,18,2,1);
insert into Zaleznosc_pytania_rola values(41,19,2,1);
insert into Zaleznosc_pytania_rola values(42,20,2,1);
insert into Zaleznosc_pytania_rola values(43,21,2,1);
insert into Zaleznosc_pytania_rola values(44,22,2,1);
insert into Zaleznosc_pytania_rola values(45,1,3,1);
insert into Zaleznosc_pytania_rola values(46,2,3,1);
insert into Zaleznosc_pytania_rola values(47,3,3,1);
insert into Zaleznosc_pytania_rola values(48,4,3,1);
insert into Zaleznosc_pytania_rola values(49,5,3,1);
insert into Zaleznosc_pytania_rola values(50,6,3,1);
insert into Zaleznosc_pytania_rola values(51,7,3,1);
insert into Zaleznosc_pytania_rola values(52,8,3,1);
insert into Zaleznosc_pytania_rola values(53,9,3,1);
insert into Zaleznosc_pytania_rola values(54,10,3,1);
insert into Zaleznosc_pytania_rola values(55,11,3,1);
insert into Zaleznosc_pytania_rola values(56,12,3,1);
insert into Zaleznosc_pytania_rola values(57,13,3,1);
insert into Zaleznosc_pytania_rola values(58,14,3,1);
insert into Zaleznosc_pytania_rola values(59,15,3,1);
insert into Zaleznosc_pytania_rola values(60,16,3,1);
insert into Zaleznosc_pytania_rola values(61,17,3,1);
insert into Zaleznosc_pytania_rola values(62,18,3,1);
insert into Zaleznosc_pytania_rola values(63,19,3,1);
insert into Zaleznosc_pytania_rola values(64,20,3,1);
insert into Zaleznosc_pytania_rola values(65,21,3,1);
insert into Zaleznosc_pytania_rola values(66,22,3,1);
insert into Zaleznosc_pytania_rola values(67,1,4,1);
insert into Zaleznosc_pytania_rola values(68,2,4,1);
insert into Zaleznosc_pytania_rola values(69,3,4,1);
insert into Zaleznosc_pytania_rola values(70,4,4,1);
insert into Zaleznosc_pytania_rola values(71,5,4,1);
insert into Zaleznosc_pytania_rola values(72,6,4,1);
insert into Zaleznosc_pytania_rola values(73,7,4,1);
insert into Zaleznosc_pytania_rola values(74,8,4,1);
insert into Zaleznosc_pytania_rola values(75,9,4,1);
insert into Zaleznosc_pytania_rola values(76,10,4,1);
insert into Zaleznosc_pytania_rola values(77,11,4,1);
insert into Zaleznosc_pytania_rola values(78,12,4,1);
insert into Zaleznosc_pytania_rola values(79,13,4,1);
insert into Zaleznosc_pytania_rola values(80,14,4,1);
insert into Zaleznosc_pytania_rola values(81,15,4,1);
insert into Zaleznosc_pytania_rola values(82,16,4,1);
insert into Zaleznosc_pytania_rola values(83,17,4,1);
insert into Zaleznosc_pytania_rola values(84,18,4,1);
insert into Zaleznosc_pytania_rola values(85,19,4,1);
insert into Zaleznosc_pytania_rola values(86,20,4,1);
insert into Zaleznosc_pytania_rola values(87,21,4,1);
insert into Zaleznosc_pytania_rola values(88,22,4,1);
insert into Zaleznosc_pytania_rola values(89,1,5,1);
insert into Zaleznosc_pytania_rola values(90,2,5,1);
insert into Zaleznosc_pytania_rola values(91,3,5,1);
insert into Zaleznosc_pytania_rola values(92,4,5,1);
insert into Zaleznosc_pytania_rola values(93,5,5,1);
insert into Zaleznosc_pytania_rola values(94,6,5,0);
insert into Zaleznosc_pytania_rola values(95,7,5,0);
insert into Zaleznosc_pytania_rola values(96,8,5,0);
insert into Zaleznosc_pytania_rola values(97,9,5,0);
insert into Zaleznosc_pytania_rola values(98,10,5,0);
insert into Zaleznosc_pytania_rola values(99,11,5,0);
insert into Zaleznosc_pytania_rola values(100,12,5,0);
insert into Zaleznosc_pytania_rola values(101,13,5,0);
insert into Zaleznosc_pytania_rola values(102,14,5,0);
insert into Zaleznosc_pytania_rola values(103,15,5,1);
insert into Zaleznosc_pytania_rola values(104,16,5,1);
insert into Zaleznosc_pytania_rola values(105,17,5,1);
insert into Zaleznosc_pytania_rola values(106,18,5,0);
insert into Zaleznosc_pytania_rola values(107,19,5,0);
insert into Zaleznosc_pytania_rola values(108,20,5,1);
insert into Zaleznosc_pytania_rola values(109,21,5,1);
insert into Zaleznosc_pytania_rola values(110,22,5,1);
insert into Zaleznosc_pytania_rola values(111,1,6,1);
insert into Zaleznosc_pytania_rola values(112,2,6,1);
insert into Zaleznosc_pytania_rola values(113,3,6,1);
insert into Zaleznosc_pytania_rola values(114,4,6,1);
insert into Zaleznosc_pytania_rola values(115,5,6,1);
insert into Zaleznosc_pytania_rola values(116,6,6,0);
insert into Zaleznosc_pytania_rola values(117,7,6,1);
insert into Zaleznosc_pytania_rola values(118,8,6,0);
insert into Zaleznosc_pytania_rola values(119,9,6,1);
insert into Zaleznosc_pytania_rola values(120,10,6,1);
insert into Zaleznosc_pytania_rola values(121,11,6,0);
insert into Zaleznosc_pytania_rola values(122,12,6,0);
insert into Zaleznosc_pytania_rola values(123,13,6,1);
insert into Zaleznosc_pytania_rola values(124,14,6,0);
insert into Zaleznosc_pytania_rola values(125,15,6,1);
insert into Zaleznosc_pytania_rola values(126,16,6,1);
insert into Zaleznosc_pytania_rola values(127,17,6,1);
insert into Zaleznosc_pytania_rola values(128,18,6,0);
insert into Zaleznosc_pytania_rola values(129,19,6,0);
insert into Zaleznosc_pytania_rola values(130,20,6,1);
insert into Zaleznosc_pytania_rola values(131,21,6,1);
insert into Zaleznosc_pytania_rola values(132,22,6,1);
insert into Zaleznosc_pytania_rola values(133,1,7,1);
insert into Zaleznosc_pytania_rola values(134,2,7,1);
insert into Zaleznosc_pytania_rola values(135,3,7,1);
insert into Zaleznosc_pytania_rola values(136,4,7,1);
insert into Zaleznosc_pytania_rola values(137,5,7,1);
insert into Zaleznosc_pytania_rola values(138,6,7,1);
insert into Zaleznosc_pytania_rola values(139,7,7,1);
insert into Zaleznosc_pytania_rola values(140,8,7,1);
insert into Zaleznosc_pytania_rola values(141,9,7,1);
insert into Zaleznosc_pytania_rola values(142,10,7,1);
insert into Zaleznosc_pytania_rola values(143,11,7,1);
insert into Zaleznosc_pytania_rola values(144,12,7,1);
insert into Zaleznosc_pytania_rola values(145,13,7,1);
insert into Zaleznosc_pytania_rola values(146,14,7,1);
insert into Zaleznosc_pytania_rola values(147,15,7,1);
insert into Zaleznosc_pytania_rola values(148,16,7,1);
insert into Zaleznosc_pytania_rola values(149,17,7,1);
insert into Zaleznosc_pytania_rola values(150,18,7,1);
insert into Zaleznosc_pytania_rola values(151,19,7,1);
insert into Zaleznosc_pytania_rola values(152,20,7,1);
insert into Zaleznosc_pytania_rola values(153,21,7,1);
insert into Zaleznosc_pytania_rola values(154,22,7,1);
insert into Zaleznosc_pytania_rola values(155,1,8,1);
insert into Zaleznosc_pytania_rola values(156,2,8,1);
insert into Zaleznosc_pytania_rola values(157,3,8,1);
insert into Zaleznosc_pytania_rola values(158,4,8,1);
insert into Zaleznosc_pytania_rola values(159,5,8,1);
insert into Zaleznosc_pytania_rola values(160,6,8,1);
insert into Zaleznosc_pytania_rola values(161,7,8,1);
insert into Zaleznosc_pytania_rola values(162,8,8,1);
insert into Zaleznosc_pytania_rola values(163,9,8,1);
insert into Zaleznosc_pytania_rola values(164,10,8,1);
insert into Zaleznosc_pytania_rola values(165,11,8,1);
insert into Zaleznosc_pytania_rola values(166,12,8,0);
insert into Zaleznosc_pytania_rola values(167,13,8,0);
insert into Zaleznosc_pytania_rola values(168,14,8,0);
insert into Zaleznosc_pytania_rola values(169,15,8,0);
insert into Zaleznosc_pytania_rola values(170,16,8,1);
insert into Zaleznosc_pytania_rola values(171,17,8,1);
insert into Zaleznosc_pytania_rola values(172,18,8,1);
insert into Zaleznosc_pytania_rola values(173,19,8,1);
insert into Zaleznosc_pytania_rola values(174,20,8,1);
insert into Zaleznosc_pytania_rola values(175,21,8,1);
insert into Zaleznosc_pytania_rola values(176,22,8,1);
insert into Zaleznosc_pytania_rola values(177,1,9,1);
insert into Zaleznosc_pytania_rola values(178,2,9,1);
insert into Zaleznosc_pytania_rola values(179,3,9,1);
insert into Zaleznosc_pytania_rola values(180,4,9,1);
insert into Zaleznosc_pytania_rola values(181,5,9,1);
insert into Zaleznosc_pytania_rola values(182,6,9,1);
insert into Zaleznosc_pytania_rola values(183,7,9,1);
insert into Zaleznosc_pytania_rola values(184,8,9,1);
insert into Zaleznosc_pytania_rola values(185,9,9,1);
insert into Zaleznosc_pytania_rola values(186,10,9,1);
insert into Zaleznosc_pytania_rola values(187,11,9,1);
insert into Zaleznosc_pytania_rola values(188,12,9,1);
insert into Zaleznosc_pytania_rola values(189,13,9,1);
insert into Zaleznosc_pytania_rola values(190,14,9,1);
insert into Zaleznosc_pytania_rola values(191,15,9,1);
insert into Zaleznosc_pytania_rola values(192,16,9,1);
insert into Zaleznosc_pytania_rola values(193,17,9,1);
insert into Zaleznosc_pytania_rola values(194,18,9,1);
insert into Zaleznosc_pytania_rola values(195,19,9,1);
insert into Zaleznosc_pytania_rola values(196,20,9,1);
insert into Zaleznosc_pytania_rola values(197,21,9,1);
insert into Zaleznosc_pytania_rola values(198,22,9,1);
insert into Zaleznosc_pytania_rola values(199,1,10,1);
insert into Zaleznosc_pytania_rola values(200,2,10,1);
insert into Zaleznosc_pytania_rola values(201,3,10,1);
insert into Zaleznosc_pytania_rola values(202,4,10,1);
insert into Zaleznosc_pytania_rola values(203,5,10,1);
insert into Zaleznosc_pytania_rola values(204,6,10,1);
insert into Zaleznosc_pytania_rola values(205,7,10,1);
insert into Zaleznosc_pytania_rola values(206,8,10,1);
insert into Zaleznosc_pytania_rola values(207,9,10,0);
insert into Zaleznosc_pytania_rola values(208,10,10,1);
insert into Zaleznosc_pytania_rola values(209,11,10,1);
insert into Zaleznosc_pytania_rola values(210,12,10,1);
insert into Zaleznosc_pytania_rola values(211,13,10,1);
insert into Zaleznosc_pytania_rola values(212,14,10,1);
insert into Zaleznosc_pytania_rola values(213,15,10,1);
insert into Zaleznosc_pytania_rola values(214,16,10,1);
insert into Zaleznosc_pytania_rola values(215,17,10,1);
insert into Zaleznosc_pytania_rola values(216,18,10,1);
insert into Zaleznosc_pytania_rola values(217,19,10,1);
insert into Zaleznosc_pytania_rola values(218,20,10,1);
insert into Zaleznosc_pytania_rola values(219,21,10,1);
insert into Zaleznosc_pytania_rola values(220,22,10,1);
insert into Zaleznosc_pytania_rola values(221,1,11,1);
insert into Zaleznosc_pytania_rola values(222,2,11,1);
insert into Zaleznosc_pytania_rola values(223,3,11,1);
insert into Zaleznosc_pytania_rola values(224,4,11,1);
insert into Zaleznosc_pytania_rola values(225,5,11,1);
insert into Zaleznosc_pytania_rola values(226,6,11,1);
insert into Zaleznosc_pytania_rola values(227,7,11,1);
insert into Zaleznosc_pytania_rola values(228,8,11,1);
insert into Zaleznosc_pytania_rola values(229,9,11,1);
insert into Zaleznosc_pytania_rola values(230,10,11,1);
insert into Zaleznosc_pytania_rola values(231,11,11,1);
insert into Zaleznosc_pytania_rola values(232,12,11,1);
insert into Zaleznosc_pytania_rola values(233,13,11,1);
insert into Zaleznosc_pytania_rola values(234,14,11,1);
insert into Zaleznosc_pytania_rola values(235,15,11,1);
insert into Zaleznosc_pytania_rola values(236,16,11,1);
insert into Zaleznosc_pytania_rola values(237,17,11,1);
insert into Zaleznosc_pytania_rola values(238,18,11,1);
insert into Zaleznosc_pytania_rola values(239,19,11,1);
insert into Zaleznosc_pytania_rola values(240,20,11,1);
insert into Zaleznosc_pytania_rola values(241,21,11,1);
insert into Zaleznosc_pytania_rola values(242,22,11,1);
insert into Zaleznosc_pytania_rola values(243,1,12,1);
insert into Zaleznosc_pytania_rola values(244,2,12,1);
insert into Zaleznosc_pytania_rola values(245,3,12,1);
insert into Zaleznosc_pytania_rola values(246,4,12,1);
insert into Zaleznosc_pytania_rola values(247,5,12,1);
insert into Zaleznosc_pytania_rola values(248,6,12,0);
insert into Zaleznosc_pytania_rola values(249,7,12,1);
insert into Zaleznosc_pytania_rola values(250,8,12,1);
insert into Zaleznosc_pytania_rola values(251,9,12,1);
insert into Zaleznosc_pytania_rola values(252,10,12,1);
insert into Zaleznosc_pytania_rola values(253,11,12,1);
insert into Zaleznosc_pytania_rola values(254,12,12,1);
insert into Zaleznosc_pytania_rola values(255,13,12,1);
insert into Zaleznosc_pytania_rola values(256,14,12,1);
insert into Zaleznosc_pytania_rola values(257,15,12,1);
insert into Zaleznosc_pytania_rola values(258,16,12,1);
insert into Zaleznosc_pytania_rola values(259,17,12,1);
insert into Zaleznosc_pytania_rola values(260,18,12,1);
insert into Zaleznosc_pytania_rola values(261,19,12,1);
insert into Zaleznosc_pytania_rola values(262,20,12,1);
insert into Zaleznosc_pytania_rola values(263,21,12,1);
insert into Zaleznosc_pytania_rola values(264,22,12,1);
insert into Zaleznosc_pytania_rola values(265,1,13,1);
insert into Zaleznosc_pytania_rola values(266,2,13,1);
insert into Zaleznosc_pytania_rola values(267,3,13,1);
insert into Zaleznosc_pytania_rola values(268,4,13,1);
insert into Zaleznosc_pytania_rola values(269,5,13,1);
insert into Zaleznosc_pytania_rola values(270,6,13,1);
insert into Zaleznosc_pytania_rola values(271,7,13,0);
insert into Zaleznosc_pytania_rola values(272,8,13,0);
insert into Zaleznosc_pytania_rola values(273,9,13,1);
insert into Zaleznosc_pytania_rola values(274,10,13,1);
insert into Zaleznosc_pytania_rola values(275,11,13,1);
insert into Zaleznosc_pytania_rola values(276,12,13,1);
insert into Zaleznosc_pytania_rola values(277,13,13,1);
insert into Zaleznosc_pytania_rola values(278,14,13,1);
insert into Zaleznosc_pytania_rola values(279,15,13,1);
insert into Zaleznosc_pytania_rola values(280,16,13,1);
insert into Zaleznosc_pytania_rola values(281,17,13,1);
insert into Zaleznosc_pytania_rola values(282,18,13,1);
insert into Zaleznosc_pytania_rola values(283,19,13,1);
insert into Zaleznosc_pytania_rola values(284,20,13,1);
insert into Zaleznosc_pytania_rola values(285,21,13,1);
insert into Zaleznosc_pytania_rola values(286,22,13,1);
insert into Zaleznosc_pytania_rola values(287,1,14,1);
insert into Zaleznosc_pytania_rola values(288,2,14,1);
insert into Zaleznosc_pytania_rola values(289,3,14,1);
insert into Zaleznosc_pytania_rola values(290,4,14,1);
insert into Zaleznosc_pytania_rola values(291,5,14,1);
insert into Zaleznosc_pytania_rola values(292,6,14,1);
insert into Zaleznosc_pytania_rola values(293,7,14,1);
insert into Zaleznosc_pytania_rola values(294,8,14,1);
insert into Zaleznosc_pytania_rola values(295,9,14,1);
insert into Zaleznosc_pytania_rola values(296,10,14,1);
insert into Zaleznosc_pytania_rola values(297,11,14,1);
insert into Zaleznosc_pytania_rola values(298,12,14,1);
insert into Zaleznosc_pytania_rola values(299,13,14,1);
insert into Zaleznosc_pytania_rola values(300,14,14,1);
insert into Zaleznosc_pytania_rola values(301,15,14,1);
insert into Zaleznosc_pytania_rola values(302,16,14,1);
insert into Zaleznosc_pytania_rola values(303,17,14,1);
insert into Zaleznosc_pytania_rola values(304,18,14,1);
insert into Zaleznosc_pytania_rola values(305,19,14,1);
insert into Zaleznosc_pytania_rola values(306,20,14,1);
insert into Zaleznosc_pytania_rola values(307,21,14,1);
insert into Zaleznosc_pytania_rola values(308,22,14,1);

